AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template to create DynamoDB TodoTable

Resources:
  TodoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: TodoTable
      PrimaryKey:
        Name: id
        Type: String
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        Enabled: true

Outputs:
  TodoTableName:
    Description: "Name of the DynamoDB table"
    Value: !Ref TodoTable
